### ISSUE TITLE
v1.3.0 To-do

### ISSUE THREAD

**Issue by ihadeed** [zyramedia/cordova-plugin-stripe#10]
- [x] create bank account number token
  - [x] Android
  - [x] iOS
  - [x] Browser
- [x] validate credit card number/expiry/cvc
  - [x] Android
  - [x] iOS
  - [x] Browser
- [x] get card type/brand
  - [X] Android
  - [x] iOS
  - [X] Browser
- [ ] validate bank account number
  - [ ] Android
  - [ ] iOS
  - [ ] Browser
- [ ] validate bank account transit number
  - [ ] Android
  - [ ] iOS
  - [ ] Browser

**Comment by ihadeed** [comment]
The bank account number/transit number validation methods were not implemented since they are only supported on Stripe.js.
