### ISSUE TITLE
TODO: V2

### ISSUE THREAD

**Issue by ihadeed** [zyramedia/cordova-plugin-stripe#14]
- [ ] Change callbacks architecture for validation methods
  - Currently, the success callback is called if the data is valid, and the error callback is called if the data is invalid. It makes more sense to ONLY use the error callback if an actual error occurs. The success callback should return a boolean that indicates whether the data is valid.
- [ ] Integrate Apple Pay
- [ ] Integrate Android Wallet (might not do it, since it's still in preview stage)

**Comment by antonmyrberg** [comment]
Is it possible to create 3d Secure payments using the plugin as is? Otherwise that'd be a great feature. Might be able to help implementing some parts of it if it doesn't already exist. 

Thanks for a great plugin.

**Comment by cwoolum** [comment]
Is there anything you are waiting on to do this or any sort of timeline? I would be interested in contributing

**Comment by ihadeed** [comment]
@cwoolum just waiting to have some time to work on this.

I see that Stripe published Stripe.js v3, and some updates to the native SDKs. I'll probably start working on a big update soon.

**Comment by RedEars** [comment]
Do you have some expected date for version 2?

**Comment by ihadeed** [comment]
@RedEars No.

**Comment by ihadeed** [comment]
Started working on it. Would appreciate it if you guys can help test the iOS side once I have it ready.

**Comment by RedEars** [comment]
@ihadeed  Sounds great! I will test when you have it ready :)

**Comment by sitexw** [comment]
I can not wait for version 2 to come out ! I need it badly for Apple Pay and Google Pay.
If I can help for anything...

**Comment by RedEars** [comment]
Do you plan to integrate sources like sepa payment?

**Comment by ihadeed** [comment]
@RedEars  No, that's not supported by the mobile SDK.

**Comment by RedEars** [comment]
@ihadeed Hmm...I can see the sources and the SEPA source type in the stripe docs: https://stripe.github.io/stripe-ios/docs/Enums/STPSourceType.html#/c:@E@STPSourceType@STPSourceTypeSEPADebit

**Comment by ihadeed** [comment]
@RedEars 
I was looking at their main docs, didn't see anything there. Thanks for sharing that link. I just checked both of their iOS + Android SDKs and it looks like they do expose methods to create sources.

**Comment by ihadeed** [comment]
No estimate at this time.
It works right now (you can try the v2 branch https://github.com/zyra/cordova-plugin-stripe/tree/v2) .. just needs few more things on the Android side. See the list above.

**Comment by ParasShahh** [comment]
@ihadeed  Is alipay working at the V2 ?

**Comment by ihadeed** [comment]
@ParasShahh Yes
https://github.com/zyra/cordova-plugin-stripe/blob/v2/www/CordovaStripe.ts#L373

**Comment by trademark2k6** [comment]
Is there any plans to update the plugin so the new SCA / 3D Secure 2 feature works?

**Comment by mtshare** [comment]
@trademark2k6 I'm waiting too... Any plans to support SCA/3D Secure 2? @ihadeed

**Comment by rgustavsson** [comment]
Is there any future for this project?
